#+TITLE: project_overview.org
#+AUTHOR: N-CRITSER
#+DATE: <2014-03-17 Mon>
#+LATEX_CLASS:article
#+LaTeX_CLASS_OPTIONS: [a4paper,6pt] 
#+OPTIONS: H:2 num:t toc:nil \n:nil @:t ::t |:t ^:{} _:{} *:t TeX:t LaTeX:t
#+LATEX_HEADER: \usepackage[margin=.75in]{geometry}


#+LaTeX_HEADER: \usepackage[T1]{fontenc} 

#+LaTeX_HEADER: \usepackage[scaled=.7]{helvet} 
#+LaTeX_HEADER: \usepackage{courier} % tt

#+LaTeX_HEADER: \linespread{1.01}

* Abstract "Talk-a-lot-Bot"
  My goal is to create a talking entity using the Arduino Uno rev3, the AdaFruit
waveshield with SD card and a speaker for audio output.  I will be painting a 
piece of ABS plastic to take on human facial features. In addition the 
talk-a-lot-bot, will have 2 8x8 led matrix blocks with an I2C interface for 
simulated eye movement.  The mouth will be formed by cutting out the ABS plastic
and placing the speaker in the hole so voice sounds come from the direction of the 
mouth.  A user, will be given a small button pad, that allows some amount 
of interaction with the talk-a-lot-bot.  I have still not decided the extent of 
this interaction.     

* Components
** Adafruit waveshield sd card module
** Speaker
** Arduino Uno - 1 boards 
** Battery pack lithium ion / ON-Off 
** 2-8x8 i2c led matrices for simulated eye movement
** adafruit libraries for graphics and sound
** ABS plastic sheets x 2  

