#+STARTUP: overview
#+AUTHOR: n-critser
#+TITLE: project-267
#+DATE: 2014-02-04

* Abstract
  Create a cool project for 267 class that forces me to learn the inner 
workings of the atmega328 microcontroller.  This may include learning the 
low level assembly instructions used by the processor itself, but is not 
limited to this level of programming.  My goal is to create an atmega328
based talking entity.  

* c-arduino basics

chaos@chaos ~/Dev/Arduino/267-proj $  avr-gcc -mmcu=atmega328p blink_led.o -o blink_led
chaos@chaos ~/Dev/Arduino/267-proj $  avr-objcopy -O ihex -R .eeprom blink_led blink_led.hex
chaos@chaos ~/Dev/Arduino/267-proj $ avrdude -F -V -c arduino -p ATMEGA328P -P /dev/ttyACM0 -b 115200 -U flash:w:blink_led.hex

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.00s

avrdude: Device signature = 0x1e950f
avrdude: NOTE: FLASH memory has been specified, an erase cycle will be performed
         To disable this feature, specify the -D option.
avrdude: erasing chip
avrdude: reading input file "blink_led.hex"
avrdude: input file blink_led.hex auto detected as Intel Hex
avrdude: writing flash (202 bytes):

Writing | ################################################## | 100% 0.04s

avrdude: 202 bytes of flash written

avrdude: safemode: Fuses OK

avrdude done.  Thank you.

