#+STARTUP: overview
#+AUTHOR: n-critser
#+TITLE: README.org for project-267
#+DATE: 2014-02-04

* Abstract
  Create a cool project for 267 class that forces me to learn the inner 
workings of the atmega328 microcontroller.  This may include learning the 
low level assembly instructions used by the processor itself, but is not 
limited to this level of programming.  My goal is to create an atmega328
based talking entity.  

* TASKS
** DONE 1st iteration Makefile 
   DEADLINE: <2014-02-04 Tue>
** TODO Chris Kuethe tutorial seperate dir
** TODO Using libraries in C
   DEADLINE: <2014-02-07 Fri>
** TODO Accessing storage in C
   DEADLINE: <2014-02-09 Sun>
** TODO Parts list for "project"
   DEADLINE: <2014-02-09 Sun>

* Compile-Pipeline

** Command Line build-&-upload
Compile C-code:
  $ avr-gcc -Os -DF_CPU=16000000UL -mmcu=atmega328p -c -o <c_file_name>.o <c_file_name>.c

Object.o to Executable: 
 $  avr-gcc -mmcu=atmega328p <c_file_name>.o -o <executable_name>

ObjectCopy to Hex:
  $  avr-objcopy -O ihex -R .eeprom <executable_name> <executable_name>.hex


Upload to Board:
  *You might have to run this as super user!! BE AWARE * 
  $ sudo avrdude -F -V -c arduino -p ATMEGA328P -P /dev/ttyACM0 -b 115200 -U flash:w:<executable_name>.hex

*** Example:
 $ avr-gcc -mmcu=atmega328p blink_led.o -o blink_led
 $ avr-objcopy -O ihex -R .eeprom blink_led blink_led.hex
 $ sudo avrdude -F -V -c arduino -p ATMEGA328P -P /dev/ttyACM0 -b 115200 -U flash:w:blink_led.hex

** Makefile build-&-upload


* Bugs-&-Fixes
** 1 
COMMAND: avrdude -F -V -c arduino -p ATMEGA328P -P /dev/ttyACM0 -b 115200 -U flash:w:blink_led.hex

ERROR:
avrdude: ser_open(): can't open device "/dev/ttyACM0": Permission denied
ioctl("TIOCMGET"): Invalid argument

ANSWER:
Run avrdude as sudo!

** 2 
*** ERROR: warning: #warning "F_CPU not defined for <util/delay.h>" [-Wcpp]
Error comes from an undefined preprocessor statement in the FILE.c
Chris's tutorial puts this define in the compilation pipeline itself
But when using a makefile that didn't fix the problem. I don't know why.

As a note, <util/delay.h> will use some defualt to define this but on the
chromebook this resulted in a super fast blinking LED that burned out after
30 seconds or so.  !!!!BE WARNED
http://www.avrfreaks.net/index.php?name=PNphpBB2&file=printview&t=126600&start=0

*** FIX:  put the define in FILE.c itself.  
This allows the compilation with the makefile without a warning 
#define F_CPU 16000000UL 


* c-arduino basics

chaos@chaos ~/Dev/Arduino/267-proj $  avr-gcc -mmcu=atmega328p blink_led.o -o blink_led
chaos@chaos ~/Dev/Arduino/267-proj $  avr-objcopy -O ihex -R .eeprom blink_led blink_led.hex
chaos@chaos ~/Dev/Arduino/267-proj $ avrdude -F -V -c arduino -p ATMEGA328P -P /dev/ttyACM0 -b 115200 -U flash:w:blink_led.hex

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.00s

avrdude: Device signature = 0x1e950f
avrdude: NOTE: FLASH memory has been specified, an erase cycle will be performed
         To disable this feature, specify the -D option.
avrdude: erasing chip
avrdude: reading input file "blink_led.hex"
avrdude: input file blink_led.hex auto detected as Intel Hex
avrdude: writing flash (202 bytes):

Writing | ################################################## | 100% 0.04s

avrdude: 202 bytes of flash written

avrdude: safemode: Fuses OK

avrdude done.  Thank you.

* Tool-Chain
** sudo apt-get install make avr-libc avrdude binutils-avr gcc-avr gdb-avr
* Tutorials
** German robot course 
svn checkout http://ornella.iwr.uni-heidelberg.de/svn/basis
** Amercan_Tutorials
*** Chris Kuethe--https://www.mainframe.cx/~ckuethe/avr-c-tutorial/
https://www.mainframe.cx/~ckuethe/avr-c-tutorial/pin_map.html


http://canthack.org/2010/12/programming-the-arduino-in-pure-c/
http://balau82.wordpress.com/2011/03/29/programming-arduino-uno-in-pure-c/
AVR C https://www.mainframe.cx/~ckuethe/avr-c-tutorial/  
http://www.mjoldfield.com/atelier/2009/02/arduino-cli.html
http://johanneshoff.com/arduino-command-line.htm
http://kartikmohta.com/tech/avr/tutorial/

* Arduino-Uno
http://arduino.cc/en/uploads/Main/arduino-uno-schematic.pd
* AVR-info
http://download-mirror.savannah.gnu.org/releases//avrdude/avrdude-doc-5.10.pdf
* Atmel-C-Stuff
http://www.atmel.com/images/doc8453.pdf
